// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: cars.sql

package db

import (
	"context"
)

const getFreeCars = `-- name: GetFreeCars :many
SELECT id, model, registration_number, fuel_level, is_reserve FROM cars WHERE is_reserve = FALSE
`

func (q *Queries) GetFreeCars(ctx context.Context) ([]Car, error) {
	rows, err := q.db.QueryContext(ctx, getFreeCars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.RegistrationNumber,
			&i.FuelLevel,
			&i.IsReserve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
